Moving resolve_patterns() from commands.py into utils.py
I needed access to resolve_patterns(), but importing the commands
module seemed to cause problems, so it seemed sensible
to move it into utils. This is the problem I encountered:

<pre>
>>> import djjsmin.commands
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ci/env_localdev/src/django-jsmin/src/djjsmin/commands.py", line 8, in <module>
    from djboss.commands import *
  File "/home/ci/env_localdev/lib/python2.6/site-packages/djboss/commands.py", line 167, in <module>
    manage = Command(manage, add_help=False, prefix_chars='')
  File "/home/ci/env_localdev/lib/python2.6/site-packages/djboss/commands.py", line 19, in __init__
    self.parser = self._make_parser(**kwargs)
  File "/home/ci/env_localdev/lib/python2.6/site-packages/djboss/commands.py", line 56, in _make_parser
    return SUBPARSERS.add_parser(self.name, **kwargs)
  File "/home/ci/env_localdev/lib/python2.6/site-packages/argparse.py", line 1085, in add_parser
    parser = self._parser_class(**kwargs)
  File "/home/ci/env_localdev/lib/python2.6/site-packages/argparse.py", line 1610, in __init__
    default_prefix = prefix_chars[0]
IndexError: string index out of range
</pre>